#!/usr/bin/env bash
# local-align-wire.sh — re-apply the W16 alignment wiring into the gitignored install copies.
#
# `.agents/` and `.claude/` are gitignored downstream install artifacts (.gitignore:8-11),
# and `local-bootstrap.sh` / `update-check.sh` overwrite them. Everything W16 puts there —
# the PreToolUse hook, its settings.json entry, and the /workflow + /prd-split skill steps —
# is therefore lost on any bootstrap or update. This script puts it all back.
#
# Idempotent. Run it after ANY bootstrap or update-check, alongside
# scripts/local-wire-orchestration.sh and scripts/local-worktree-mode.sh.
#
#   ./scripts/local-align-wire.sh
#   ./scripts/local-align-wire.sh --check    # report what is missing, change nothing

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

missing=0
note() { echo "  $*"; }
need() { missing=1; note "MISSING: $*"; }

# ---------------------------------------------------------------- 1. the hook itself
HOOK=".claude/hooks/align-guard.sh"
if [ ! -x "$HOOK" ]; then
  need "$HOOK"
  if [ "$CHECK" = "0" ]; then
    mkdir -p .claude/hooks
    cat > "$HOOK" <<'HOOKEOF'
#!/usr/bin/env bash
# align-guard.sh — PreToolUse guard for Edit / Write / NotebookEdit.
# Regenerated by scripts/local-align-wire.sh. See docs/DECISIONS-LEDGER.md W16b.
set -uo pipefail
[ "${FRNDOS_ALIGN_OFF:-0}" = "1" ] && exit 0
ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
ALIGN="$ROOT/scripts/local-align.sh"
[ -x "$ALIGN" ] || exit 0
payload="$(cat)"
file="$(printf '%s' "$payload" | python3 -c 'import json,sys
try:
    d = json.load(sys.stdin)
    print((d.get("tool_input") or {}).get("file_path") or "")
except Exception:
    print("")' 2>/dev/null)"
[ -n "$file" ] || exit 0
case "$file" in
  "$ROOT"/*) rel="${file#"$ROOT"/}" ;;
  /*)        exit 0 ;;
  *)         rel="$file" ;;
esac
svc="${rel%%/*}"
[ "$svc" != "$rel" ] || exit 0
expected="$("$ALIGN" --expected "$svc" 2>/dev/null)" || exit 0
[ -n "$expected" ] || exit 0
current="$(git -C "$ROOT/$svc" branch --show-current 2>/dev/null)" || exit 0
[ -n "$current" ] || exit 0
[ "$current" = "$expected" ] && exit 0
cat >&2 <<MSG
BLOCKED by align-guard: $svc is on the wrong branch for the active feature.

  file:     $rel
  $svc is on:   $current
  expected:     $expected

Do NOT edit around this. Pick one:
  1. Align the workspace:   ./scripts/local-align.sh --apply
  2. This is separate work:  /workflow start <slug>, then align
  3. Deliberate one-off:     FRNDOS_ALIGN_OFF=1 for this session, and say so out loud

See the whole picture first: ./scripts/local-align.sh
MSG
exit 2
HOOKEOF
    chmod +x "$HOOK"
    note "wrote $HOOK"
  fi
fi

# ---------------------------------------------------------------- 2. settings.json entry
if ! python3 -c '
import json, sys
h = (json.load(open(".claude/settings.json")).get("hooks") or {}).get("PreToolUse") or []
sys.exit(0 if any("align-guard" in str(e) for e in h) else 1)
' 2>/dev/null; then
  need ".claude/settings.json PreToolUse -> align-guard.sh"
  if [ "$CHECK" = "0" ]; then
    python3 - <<'PY'
import json, collections
p = ".claude/settings.json"
s = json.load(open(p), object_pairs_hook=collections.OrderedDict)
entry = collections.OrderedDict([
    ("matcher", "Edit|Write|NotebookEdit"),
    ("hooks", [collections.OrderedDict([
        ("type", "command"),
        ("command", "$CLAUDE_PROJECT_DIR/.claude/hooks/align-guard.sh"),
    ])]),
])
pre = s.setdefault("hooks", collections.OrderedDict()).setdefault("PreToolUse", [])
if not any("align-guard" in str(e) for e in pre):
    pre.append(entry)
json.dump(s, open(p, "w"), indent=2, ensure_ascii=False)
open(p, "a").write("\n")
PY
    note "wired .claude/settings.json"
  fi
fi

# ---------------------------------------------------------------- 3. skill steps
patch_skill() {
  local file="$1" marker="$2" py="$3"
  [ -f "$file" ] || { note "SKIP (absent): $file"; return; }
  if grep -q "$marker" "$file"; then return; fi
  need "$file — $marker"
  [ "$CHECK" = "1" ] && return
  python3 - "$file" <<PY
import sys
p = sys.argv[1]
s = open(p).read()
$py
open(p, "w").write(s)
PY
  note "patched $file"
}

patch_skill ".agents/skills/workflow/SKILL.md" "local-align.sh" '
old = """6. If on a different git branch, inform user: \"Feature `<slug>` is on branch `{branch}`. Switch with: `git checkout {branch}`\""""
new = """6. **Align the whole workspace — do not merely advise.** Run `./scripts/local-align.sh <slug>`
   to show the table, then `./scripts/local-align.sh <slug> --apply` to move every repo:
   in-scope services (`features[<slug>].services`) go to `features[<slug>].branch`; every
   other service parks on its own default branch. `workspace-root` is pinned and never moved.
   The script refuses on tracked-file changes and on `release/*` branches (`--force-release`
   to override) — report what it refused, never work around it."""
if old in s:
    s = s.replace(old, new)
old2 = """   - PRs: list `{pr_urls}` entries (service -> URL) or \"not submitted\""""
old2 = old2.replace("->", chr(8594))
new2 = old2 + """
3. **Run `./scripts/local-align.sh` (read-only) and show its table.** It exits 1 on drift."""
if old2 in s:
    s = s.replace(old2, new2)
old3 = """     \"branch\": null,
     \"service_prds\": {},"""
new3 = """     \"branch\": null,
     \"services\": [],
     \"service_prds\": {},"""
if old3 in s:
    s = s.replace(old3, new3)
'

patch_skill ".agents/skills/prd-split/SKILL.md" "local-align.sh" '
old = "9. Update `.workflow-state.json` `service_prds` with paths."
new = """9. Update `.workflow-state.json` `service_prds` with paths, and set **`services`** to the same
   keys as workspace *directory* names (`orchestration`, not `frnd-orchestration`). `services`
   is what `scripts/local-align.sh` and the `align-guard` hook enforce — leaving it `null`
   turns the guard off for this feature.

9b. Run `./scripts/local-align.sh <slug> --apply` so every in-scope service is on the new feature
   branch and every uninvolved service is parked. Report the table.

9c. Original step 9 continues:"""
if old in s and "local-align.sh" not in s:
    s = s.replace(old, new + " " + old[3:], 1)
'

echo
if [ "$missing" = "0" ]; then
  echo "align wiring: present."
elif [ "$CHECK" = "1" ]; then
  echo "align wiring: INCOMPLETE — run ./scripts/local-align-wire.sh"
  exit 1
else
  echo "align wiring: restored."
fi
